apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "django-backend.fullname" . }}
  labels:
    app: django-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: django-backend
  template:
    metadata:
      labels:
        app: django-backend
    spec:
      imagePullSecrets:
      - name: gitlab-registry      
      containers:
        - name: django
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          readinessProbe:
            httpGet:
              path: {{ .Values.backend.readinessProbe.path }}
              port: {{ .Values.backend.readinessProbe.port }}
            initialDelaySeconds: {{ .Values.backend.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.readinessProbe.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.backend.livenessProbe.path }}
              port: {{ .Values.backend.livenessProbe.port }}
            initialDelaySeconds: {{ .Values.backend.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.livenessProbe.periodSeconds }}
          env:
          # Переменные из secret
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: aff-db-secret
                key: db-password
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: aff-db-secret
                key: db-name
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: aff-db-secret
                key: db-user
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: aff-db-secret
                key: db-host
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: aff-db-secret
                key: db-port            
