apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
# Name the Ingress resource
  name: aff-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-{{ .Values.global.prefix }}-certificate
spec:
  tls:
    - secretName: {{ .Values.global.prefix }}.letsencrypt.key.tls
      hosts:
        - {{ .Values.ingress.host }}
  # Create Ingress routing rules
  rules:
  # Replace with your domain name
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.global.prefix }}-backend
              port:
                number: 8000
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.global.prefix }}-frontend
              port:
                number: 80

