global:
  prefix: aff

backend:
  replicaCount: 2
  image:
    repository: gitlab.cleverbots.ru:4567/edu/aaf/backend
    tag: 0.0.21
    pullPolicy: IfNotPresent
  containerPort: 8000
  service:
    port: 8000
  readinessProbe:
    path: /api/message
    port: 8000
    initialDelaySeconds: 10
    periodSeconds: 5
  livenessProbe:
    path: /api/message
    port: 8000
    initialDelaySeconds: 30
    periodSeconds: 10

frontend:
  replicaCount: 2
  image:
    repository: gitlab.cleverbots.ru:4567/edu/aaf/frontend
    tag: 0.0.23
    pullPolicy: IfNotPresent
  containerPort: 80
  service:
    port: 80
  readinessProbe:
    path: /
    port: 80
    initialDelaySeconds: 5
    periodSeconds: 5
  livenessProbe:
    path: /
    port: 80
    initialDelaySeconds: 10
    periodSeconds: 10

ingress:
  enabled: true
  className: traefik
  host: aff.dswz.ru
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-strip-api-prefix@kubernetescrd
  path: / 
  tls:
    enabled: true
    letsEncrypt:
      enabled: true
      email: peter@kurishev.ru  # Email для Let's Encrypt
      production: true  # true для продакшена, false для теста (staging)
    

middleware:
  enabled: true
  name: strip-api-prefix
  namespace: default

additionalVolumes:
  - name: acme-json
    secret:
      secretName: acme-json-secret

additionalVolumeMounts:
  - name: acme-json
    mountPath: /data/acme.json
    subPath: acme.json
